#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
    echo -e "\nUsage: ${0} [repo-url]\n"
    exit 1
fi

git init \
&& git add . \
&& git commit -m "Initial commit" \
&& git branch -M main \
&& git remote add origin ${1} \
&& git push -u origin main
